pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xataz/.docker/config.json:/root/.docker/config.json
    commands:
      - chmod +x .ci/build.sh
      - ls
      - pwd
      - .ci/build.sh push
